sudo: false
language: php
services:
  - mysql
notifications:
  slack: wp-media:nnBz5DMaiRLNaEqIStaUgygW
  email:
    on_success: never
    on_failure: never
branches:
  only:
  - master
  - develop
  - /branch-.*$/
cache:
  directories:
  - vendor
  - $HOME/.composer/cache
matrix:
  fast_finish: true
  include:
  - php: 7.4
    env: WP_VERSION=latest
  - php: 7.3
    env: WP_VERSION=latest
  - php: 7.2
    env: WP_VERSION=latest
  - php: 5.6
    env: WP_VERSION=latest
  - name: Legacy
    php: 5.6
    env: WP_VERSION=4.9.11
  - name: Coding Standards
    php: 7.3
    env: WP_TRAVISCI=phpcs
before_install:
  # Unless we need XDebug, disable it for improved performance.
  - phpenv config-rm xdebug.ini || return 0
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ -f composer.lock ]] ; then
      rm composer.lock
    fi
  - composer remove --dev phpstan/phpstan szepeviktor/phpstan-wordpress
install:
  - composer install --prefer-dist --no-interaction
before_script:
- |
  if [[ ! -z "$WP_VERSION" ]] ; then
    bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  fi
script:
- |
  if [[ "$WP_TRAVISCI" == "phpcs" ]]; then
    composer phpcs
  else
    composer run-tests
  fi
