on: delete

name: Delete WP test Instance
jobs:
  delete:
    if: (github.event.ref_type == 'branch') && ( startsWith(github.event.ref, 'dev-') || startsWith(github.event.ref, 'ga-') )
    name: delete WP instance from cluster
    runs-on: ubuntu-latest
    steps:
      - name: delete from cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: |
            helm delete ${{ github.event.ref }} -n ${{ github.event.ref }}
            kubectl delete namespace ${{ github.event.ref }}
