# This is a basic workflow to help you get started with Actions

name: Dynamic lists fallback update

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_WORKFLOW_TOKEN }}

      - name: get latest dynamic lists
        id: getDynamicLists
        run: |
          echo "::set-output name=lists::$(curl -s https://b.rucss.wp-rocket.me/api/exclusions/list)"

      - name: Save Default Lists
        id: saveDynamicLists
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "dynamic-lists.json"
          json: ${{ steps.getDynamicLists.outputs.lists }}
          dir: '/'

      - name: Commit Default Lists JSON file
        if: ${{ steps.saveDynamicLists.outcome == 'success' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update dynamic lists
          commit_user_name: WP Media GitHub Actions Bot

      - name: get latest incompatible plugins lists
        id: getIncompatiblePluginsLists
        run: |
          echo "::set-output name=lists::$(curl -s https://b.rucss.wp-rocket.me/api/incompatible-plugins/list)"

      - name: Save IncompatiblePlugins Lists
        id: saveIncompatiblePluginsLists
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "dynamic-lists-incompatible-plugins.json"
          json: ${{ steps.getIncompatiblePluginsLists.outputs.lists }}
          dir: '/'

      - name: Commit IncompatiblePlugins JSON file
        if: ${{ steps.saveIncompatiblePluginsLists.outcome == 'success' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update incompatible plugins dynamic lists
          commit_user_name: WP Media GitHub Actions Bot

      - name: get latest DelayJS lists
        id: getDynamicDelayJSLists
        run: |
          echo "::set-output name=lists::$(curl -s https://b.rucss.wp-rocket.me/api/delay-js-exclusions/list)"

      - name: Save DelayJS Lists
        id: saveDynamicDelayJSLists
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "dynamic-lists-delayjs.json"
          json: ${{ steps.getDynamicDelayJSLists.outputs.lists }}
          dir: '/'

      - name: Commit DelayJS JSON file
        if: ${{ steps.saveDynamicDelayJSLists.outcome == 'success' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update delay JS dynamic lists
          commit_user_name: WP Media GitHub Actions Bot
