on:
  release:
    types: 
      - published
      - edited

name: Deploy Rocket Plugin on Dev
jobs:
  deploy:
    name: Deploy Rocket Plugin on Dev
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v1

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Run composer
        run: composer install --no-scripts --no-dev
  
      - name: Zip Folder
        run: zip -r /tmp/__wp-rocket__${GITHUB_REF##*v}.zip .

      # Use Openstack Swift to upload the zip to OVH block storage
      # We post a header to instruct the file to be deleted after 10 minutes
      - name: Upload Zip
        uses: iksaku/openstack-swift-action@v3.8.1
        env:
          OS_AUTH_URL: 'https://auth.cloud.ovh.net/v3'
          OS_PASSWORD: ${{ secrets.OBJECT_STORAGE_PASSWORD }}
          OS_PROJECT_NAME: ${{ secrets.OBJECT_STORAGE_PROJECT }}
          OS_PROJECT_ID: ${{ secrets.OBJECT_STORAGE_PROJECT_ID }}
          OS_REGION_NAME: 'SBG5'
          OS_USERNAME: ${{ secrets.OBJECT_STORAGE_USERNAME }}
          OS_USER_DOMAIN_NAME: 'Default'
        with:
          args: |
            upload rocket-plugin /tmp/__wp-rocket__${GITHUB_REF##*v}.zip
            post --header "X-Delete-After: 600" rocket-plugin __wp-rocket__${GITHUB_REF##*v}.zip

      # Call the webhook on AWX to fetch and deploy the zip
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v1
        env:
          webhook_url: https://awx.wp-media.me:443/api/v2/job_templates/34/github/
          webhook_secret: ${{ secrets.WEBHOOK_KEY_PLUGIN }}
