on:
  release:
    types: 
      - published
      - edited

name: Deploy Rocket Plugin on Dev
jobs:
  deploy:
    name: Deploy Rocket Plugin on Dev
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v1

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Download zip
        run: |
          wget "https://github.com/wp-media/wp-rocket/archive/trunk.zip"
          unzip trunk.zip
          mv wp-rocket-trunk wp-rocket
        working-directory: /tmp

      - name: Run composer
        run: composer install --no-scripts --no-dev
        working-directory: /tmp/wp-rocket
  
      - name: Zip Folder
        run: zip -r __wp-rocket_${GITHUB_REF##*v}.zip wp-rocket
        working-directory: /tmp

      - name: Install Swift
        run: |
          sudo apt update
          sudo apt install python3-swiftclient -y
      # Use Openstack Swift to upload the zip to OVH block storage
      # We post a header to instruct the file to be deleted after 10 minutes
      - name: Upload Zip
        env:
          OS_AUTH_URL: "https://auth.cloud.ovh.net/v3"
          OS_PASSWORD: ${{ secrets.OBJECT_STORAGE_PASSWORD }}
          OS_PROJECT_NAME: ${{ secrets.OBJECT_STORAGE_PROJECT }}
          OS_PROJECT_ID: ${{ secrets.OBJECT_STORAGE_PROJECT_ID }}
          OS_REGION_NAME: "SBG"
          OS_USERNAME: ${{ secrets.OBJECT_STORAGE_USERNAME }}
          OS_USER_DOMAIN_NAME: "Default"
        working-directory: /tmp
        run: |
          /usr/bin/swift upload rocket-plugin __wp-rocket__${GITHUB_REF##*v}.zip
          /usr/bin/swift post --header "X-Delete-After: 600" rocket-plugin __wp-rocket_${GITHUB_REF##*v}.zip
        
            
      # Call the webhook on AWX to fetch and deploy the zip
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v1
        env:
          webhook_type: 'json-extended'
          webhook_url: https://awx.wp-media.me:443/api/v2/job_templates/34/github/
          webhook_secret: ${{ secrets.WEBHOOK_KEY_PLUGIN }}
