name: Run unit tests on PR
on: 
  pull_request
jobs:
  test:
    name: PHP ${{ matrix.php }} WP ${{ matrix.wp }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '5.6', '7.0', '7.4', '8.0' ]
        wp: [ '5.2', '5.3', '5.4', '5.5', '5.6', 'latest' ]
        exclude:
          - php: 7.4
            wp: 5.2
          - php: 8.0
            wp: 5.2
          - php: 8.0
            wp: 5.3
          - php: 8.0
            wp: 5.4
          - php: 8.0
            wp: 5.5
    services:
      database:
        image: mysql:5.6
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          extensions: mysql
          coverage: none

      - name: Tool versions
        run: |
          php --version
          composer --version

      - name: Get cached composer directories
        uses: actions/cache@v2
        with:
          path: ./vendor
          key: ${{ runner.os }}-${{ hashFiles('./composer.lock') }}

      - name: Setup and install composer
        run: composer install

      - name: Add PHP8 Compatibility.
        run: |
          # PHP 5.6 and 7.0: use PhpUnit 5.7
          if [ "$(php -r "echo version_compare( PHP_VERSION, '7.1', '<' );")" ]; then
              curl -L https://phar.phpunit.de/phpunit-5.7.phar -o /tmp/phpunit
              chmod +x /tmp/phpunit
              rm ./vendor/bin/phpunit
              mv /tmp/phpunit ./vendor/bin/phpunit
          # PHP 8.0 or higher: use our custom fork of PhpUnit 7.5
          elif [ "$(php -r "echo version_compare( PHP_VERSION, '8.0', '>=' );")" ]; then
              curl -L https://github.com/woocommerce/phpunit/archive/add-compatibility-with-php8-to-phpunit-7.zip -o /tmp/phpunit-7.5-fork.zip
              unzip -d /tmp/phpunit-7.5-fork /tmp/phpunit-7.5-fork.zip
              composer --working-dir=/tmp/phpunit-7.5-fork/phpunit-add-compatibility-with-php8-to-phpunit-7 install
              rm ./vendor/bin/phpunit
              ln -sf /tmp/phpunit-7.5-fork/phpunit-add-compatibility-with-php8-to-phpunit-7/phpunit ./vendor/bin/phpunit
           fi 

      - name: Init DB and WP
        run: ./tests/bin/install.sh woo_test root root 127.0.0.1 ${{ matrix.wp }}

      - name: Run tests (single site)
        run: |
          ./vendor/bin/phpunit --version
          ./vendor/bin/phpunit -c ./tests/phpunit.xml.dist

      - name: Run tests (multisite)
        run: |
          ./vendor/bin/phpunit --version
          WP_MULTISITE=1 ./vendor/bin/phpunit -c ./tests/phpunit.xml.dist
